- name: RHEL | Install JBOSS
  yum:
    name: "{{ jboss_eap_package_list }}"
    state: present
  tags:
    - jboss_eap

- name: Copy EAP configuration
  template:
    src: sysconfig_eap{{ jboss_eap_base_version | int }}.j2
    dest: "{{ jboss_eap_service_conf_file }}"
  notify: restart eap
  tags:
    - jboss_eap
    - jboss_config

- name: RHEL | Start and enable JBOSS
  service:
    name: "{{ jboss_eap_service_name }}"
    state: started
    enabled: yes
  tags:
    - jboss_eap
