- name: RHEL | Install JBOSS
  yum:
    name: "{{ jboss_eap_package_list }}"
    state: present
  register: jboss_yum_install
  tags:
    - jboss_eap

- name: RHEL | Copy EAP service configuration ({{ jboss_eap_service_conf_file }})
  template:
    src: sysconfig_eap{{ jboss_eap_base_version | int }}.j2
    dest: "{{ jboss_eap_service_conf_file }}"
  notify: restart eap
  tags:
    - jboss_eap
    - jboss_config

- name: RHEL | Copy EAP runtime configuration ({{ jboss_eap_runtime_conf_file }})
  template:
    src: runtime_{{ jboss_eap_configuration }}.conf.j2
    dest: "{{ jboss_eap_runtime_conf_file }}"
    owner: "{{ jboss_eap_user }}"
    group: "{{ jboss_eap_group }}"
  notify: restart eap
  tags:
    - jboss_eap
    - jboss_config

- name: RHEL | Copy EAP server configuration ({{ jboss_eap_server_config }})
  copy:
    src: "{{ jboss_eap_server_config }}"
    dest: "{{ jboss_eap_jboss_home }}/{{ jboss_eap_server_config }}"
  notify: restart eap
  tags:
    - jboss_eap
    - jboss_config

- name: RHEL | Create default JBoss admin user
  command: "{{ jboss_eap_jboss_home }}/bin/add-user.sh -s -r ManagementRealm -u {{ jboss_eap_admin_user }} -p {{ jboss_eap_admin_password }}"
  when: jboss_yum_install.changed
  tags:
    - jboss_eap

- name: RHEL | Start and enable JBOSS
  service:
    name: "{{ jboss_eap_service_name }}"
    state: started
    enabled: yes
  tags:
    - jboss_eap
